name: version-initializer
on:
  workflow_dispatch:
    inputs:
      versioning:
        description: 'Versioning strategy to use'
        type: choice
        options:
          - semantic
          - date-timestamp-commit
        default: date-timestamp-commit
      semantic_version:
        description: 'Semantic version to use (only if semantic versioning is selected)'
        type: string
        default: '1.0.0'
        required: false

jobs:
  initialize-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.init_version.outputs.version }}
    steps:
      - name: Initialize version
        id: init_version
        run: |
          if [ "${{ github.event.inputs.versioning }}" = "semantic" ]; then
            echo "Using semantic versioning"
            echo "version=${{ github.event.inputs.semantic_version }}" >> $GITHUB_OUTPUT
          else
            echo "Using date-timestamp-commit versioning"
            echo "version=$(date +%Y%m%d-%H%M%S)-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          fi
      - name: Output version
        run: |
          echo "Initialized version: ${{ steps.init_version.outputs.version }}"